#!/bin/bash
[ $UID != 0 ] && echo must run as root >&2 && exit 1

LS_OPTIONS='-r'
[[ "$1" == "-p" || "$1" == --previous ]] && LS_OPTIONS=''

export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
user=$(logname)

eval background_current=$(su $user -c 'gsettings get org.gnome.desktop.background picture-uri')
background_current="${background_current#file://}"
index_current_background=-1

index=0
wallpapers=()
while read wallpaper; do
  if file --brief --mime-type "$wallpaper" | grep 'image/' &>/dev/null; then
    wallpapers=("${wallpapers[@]}" "$wallpaper")
    if [ "$wallpaper" = "$background_current" ]; then
      index_current_background=$index
    fi
    ((index++))
  fi
done <<<$(eval ls -dt1 $LS_OPTIONS ~$user/Pictures/Wallpapers/*)

wallpaper_count=${#wallpapers[@]}

index_next_background=$((index_current_background+1))
if [[ $index_next_background == $wallpaper_count ]]
then
   index_next_background=0
fi

background_next="${wallpapers[$index_next_background]}"

set-gdm-theme -s -b "$background_next" &>/dev/null
su $user -c "gsettings set org.gnome.desktop.background picture-uri 'file://$background_next'" &>/dev/null
