" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim80/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" do not load defaults if ~/.vimrc is missing
"let skip_defaults_vim=1
set number

" TAB = 3 Spaces and n TABs (at line-start) becomes 3n Spaces
set autoindent
set expandtab
set copyindent
set preserveindent
set shiftround
set smartindent
set smarttab
"set softtabstop=0
set shiftwidth=3
set tabstop=3
set ignorecase
set smartcase   
"set mouse=nvi
"set cursorline
"set cursorcolumn
"highlight CursorLine ctermbg=Yellow cterm=bold guibg=2b2b2b
"highlight CursorColumn ctermbg=Yellow cterm=bold guibg=2b2b2b
set termguicolors
map <C-y> "+y
map <C-p> "+p
